language: go

go:
  - "1.19.x"
  - "1.18.x"
  - tip

os:
- linux
- osx
- windows

before_install:
  - go get -t -v ./...

before_script:
  - go vet ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)