name: Lint & Test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  lint-and-test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3