name: Lint & Test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  lint-and-test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Lint & Test
        run: |
          go get -t -v ./...
          go vet ./...
          go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3